---
# etcd cluster configuration
etcd_cluster_name: gitlab-etcd-cluster
etcd_initial_cluster_state: new
etcd_peer_port: 2380
etcd_client_port: 2379
etcd_data_dir: /var/lib/etcd
etcd_user: etcd
etcd_group: etcd
